---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiki
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wikijs-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: wikijs
        property: user
    - secretKey: DB_PASS
      remoteRef:
        key: wikijs
        property: pass
    - secretKey: DB_NAME
      remoteRef:
        key: wikijs
        property: database
    - secretKey: DB_HOST
      remoteRef:
        key: wikijs
        property: server
    - secretKey: DB_PORT
      remoteRef:
        key: wikijs
        property: db_port
    - secretKey: DB_TYPE
      remoteRef:
        key: wikijs
        property: db_type


