---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/requarks/wiki
      tag: latest
    service:
      main:
        ports:
          http:
            port: &port 3000
    probes:
      livenessProbe:
        httpGet:
          path: /healthz
          port: http
      readinessProbe:
        httpGet:
          path: /healthz
          port: http
      startupProbe:
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 60
        httpGet:
          path: /healthz
          port: http
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    postgresql:
      enabled: false
    envFrom:
      - secretRef:
          name: wikijs-secret
    # - name: DB_TYPE
    # - name: DB_HOST
    # - name: DB_PORT
    # - name: DB_NAME
    # - name: DB_USER
    # - name: DB_SSL
    # - name: DB_PASS




