apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minecraft
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-metallb
    - name: cluster-apps-nfs-external
  path: ./kubernetes/apps/games/minecraft/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: minecraft
      namespace: games
  interval: 30m
  retryInterval: 1m
  timeout: 3m
