---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./overseerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./calibre-web/ks.yaml
