apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-minecraft
  namespace: minecraft
data:
  values.yaml: |-
    image:
      repository: itzg/minecraft-server
      tag: 2022.16.0-java17
    strategyType: Recreate
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"
    resources:
      requests:
        memory: 6Gi
        cpu: 250m
      limits:
        memory: 10Gi
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "will-mc.${SECRET_DOMAIN}"
    extraEnv:
      MODS: "https://github.com/EssentialsX/Essentials/releases/download/2.19.7/EssentialsX-2.19.7.jar, https://cdn.modrinth.com/data/Lu3KuzdV/versions/mvLpRWww/CoreProtect-21.3.jar"
      ENABLE_AUTOPAUSE: FALSE
      SPIGET_RESOURCES: "74354,28140,102931"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      forceReDownload: true
      jvmOpts: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      memory: 4096M
      difficulty: normal
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: survival
      motd: "will.techringer.net\n\u00A76\u00A7lwalker survival\u00A7r\u00A7l - \u00A7r\u00A7c\u00A7lSMP\u00A7r\n"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-23.png
      loadBalancerIP: 10.11.230.49
      rcon:
        enabled: false
        port: 25575
        password: "${RCON_PASSWORD}"
        serviceType: LoadBalancer
      extraPorts:
        - name: map
          containerPort: 8123
          service:
            enabled: true
            type: ClusterIP
            port: 8123
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
              external-dns.home.arpa/enabled: "true"
              hajimari.io/icon: video-input-antenna
            hosts:
            - host: &host "will-mc.${SECRET_DOMAIN}"
              paths:
              - path: /
                pathType: Prefix
            tls:
            - hosts:
              - *host
        - name: geyser
          containerPort: 19132
          protocol: UDP
          service:
            enabled: true
            type: LoadBalancer
            port: 19132
            loadBalancerIP: 10.11.230.49
          ingress:
            enabled: false
