---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
