---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/itzg/minecraft-server-charts
  timeout: 3m
