---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  releaseName: esphome
  interval: 5m
  chart:
    spec:
      chart: esphome
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: esphome/esphome
      tag: 2022.12.6
    env:
      TZ: "${TIMEZONE}"
      ESPHOME_DASHBOARD_USE_PING: true
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - host: &host "esp.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - *host
          secretName: tls.esphome
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config

    resources:
      requests:
        cpu: 15m
        memory: 79M
