---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cyberchef
  namespace: security
spec:
  values:
    image:
      repository: docker.io/mpepping/cyberchef
      tag: v9.55.0

    env:
      TZ: ${TZ}

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "cyberchef.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: hammer-wrench
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        memory: 79M
