---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: kube-system
resources:
  - ./rbac.yaml
  - ./daemonset.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: disabled
