---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-proxy-secret
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    #name: minecraft-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: LB_IP
      remoteRef:
        key: minecraft
        property: LB_IP
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: minecraft
        property: RCON_PASSWORD
    - secretKey: RCON_PORT
      remoteRef:
        key: minecraft
        property: RCON_PORT

