---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-proxy
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-proxy
    creationPolicy: Owner
  dataFrom:
    - extract:
        # LB_IP, RCON_PASSWORD, RCON_PORT
        key: minecraft
