kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: botpress-claim
  namespace: bots
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
