---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email_host: "{{ .authentik_email_host }}"
        email_sender: "{{ .authentik_email_sender }}"
        database_name: "{{ .authentik_postgresql_database }}"
        postgresql_user: "{{ .authentik_postgresql_user }}"
        postgresql_password: "{{ .authentik_postgresql_password }}"
        cookie_secret: "{{ .authentik_cookie_secret }}"

  dataFrom:
    - extract:
        key: authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-database-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-database-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        port: "{{ .postgresql_postgresql_port }}"
        host: "{{ .postgresql_host }}"

  dataFrom:
    - extract:
        key: database-main
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgresql_$1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-geoip-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-geoip-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        account_id: "{{ .maxmind_account_id }}"
        license_key: "{{ .maxmind_license_key }}"

  dataFrom:
    - extract:
        key: maxmind
      rewrite:
        - regexp:
            source: "(.*)"
            target: "maxmind_$1"

