apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: authentik-embedded-outpost
    namespace: security
spec:
    ingressClassName: nginx
    rules:
        - host: authentik."${SECRET_DOMAIN}"
          http:
              paths: /outpost.goauthentik.io
              pathType: Prefix
              backend:
                  serviceName: ak-outpost-authentik-embedded-outpost
                  servicePort: 9000
