apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: authentik-outpost
    namespace: security
spec:
    rules:
        - host: authentik."${SECRET_DOMAIN}"
          http:
              paths: /outpost.goauthentik.io
              pathType: Prefix
              backend:
                  service:
                    name: authentik-outpost
                    port:
                        number: 9000
