---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vpa
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/vpa/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-thanos
