---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wikijs
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wikijs-secret
    creationPolicy: Owner
  data:
    - secretKey: USERNAME
      remoteRef:
        key: wikijs
        property: username
    - secretKey: PASSWORD
      remoteRef:
        key: wikijs
        property: password
    - secretKey: DATABASE
      remoteRef:
        key: wikijs
        property: DATABASE
    - secretKey: SERVER
      remoteRef:
        key: wikijs
        property: server

