---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: wiki
      sourceRef:
        kind: HelmRepository
        name: wikijs-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/requarks/wiki
      tag: latest
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: wikijs-secret
      valuesKey: SERVER
      targetPath: postgresql.postgresqlHost
    - kind: Secret
      name: wikijs-secret
      valuesKey: DATABASE
      targetPath: postgresql.postgresqlDatabase
    - kind: Secret
      name: wikijs-secret
      valuesKey: USERNAME
      targetPath: postgresql.postgresqlUser
    - kind: Secret
      name: wikijs-secret
      valuesKey: PASSWORD
      targetPath: postgresql.postgresqlPassword





