---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: valheim-secret
    creationPolicy: Owner
  dataFrom:
    # WORLD_NAME, SERVER_NAME, SERVER_PASS, ADMINLIST_IDS, SUPERVISOR_HTTP_PASS, SUPERVISOR_HTTP_USER
    - extract:
        key: valheim
