---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim-secret
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: valheim-secret
    creationPolicy: Owner
  data:
    - secretKey: WORLD_NAME
      remoteRef:
        key: valheim
        property: WORLD_NAME
    - secretKey: SERVER_NAME
      remoteRef:
        key: valheim
        property: SERVER_NAME
    - secretKey: SERVER_PASS
      remoteRef:
        key: valheim
        property: SERVER_PASS
    - secretKey: ADMINLIST_IDS
      remoteRef:
        key: valheim
        property: ADMINLIST_IDS
    - secretKey: SUPERVISOR_HTTP_PASS
      remoteRef:
        key: valheim
        property: SUPERVISOR_HTTP_PASS
    - secretKey: SUPERVISOR_HTTP_USER
      remoteRef:
        key: valheim
        property: SUPERVISOR_HTTP_USER
    - secretKey: LB_VALHEIM
      remoteRef:
        key: valheim
        property: LB_VALHEIM
