---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      # nameOverride: valheim
      annotations:
        reloader.stakater.com/search: "true"

    image:
      repository: lloesche/valheim-server
      tag: latest
      pullPolicy: Always

    # env:
    #   ...
    envFrom:
      - secretRef:
          name: valheim-secret
      - configMapRef:
          name: valheim-config
      - configMapRef:
          name: valheimplus-config

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        #loadBalancerIP:
        ports:
          http:
            port: 80
          steam1:
            port: 2456
            protocol: UDP
          steam2:
            port: 2457
            protocol: UDP
          steam3:
            port: 2458
            protocol: UDP
          supervisor:
            port: 9001
            protocol: TCP

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "valheim.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: tls.valheim

    persistence:
      config:
        enabled: true
        existingClaim: valheim-nfs-config
        subPath:
          - path: games/valheim/config
            mountPath: /config
          - path: games/valheim/data
            mountPath: /opt/valheim

    podSecurityContext:
      supplementalGroups:
        - 100 # Users
        - 65537 # NAS Permission group

    resources:
      requests:
        cpu: 511m
        memory: 5528M

    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: kubernetes.io/hostname
    #               operator: In
    #               values:
    #                 - "hp1"
  valuesFrom:
    - kind: Secret
      name: valheim-secret
      valuesKey: LB_VALHEIM
      targetPath: service.main.loadBalancerIP
