---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./configmap-valheim.yaml
  - ./configmap-valheimplus.yaml
  - ./pvc.yaml
  - ./externalsecret.yaml
