---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-nfs-config
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi
