---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: vector-aggregator-configmap
    files:
      - vector.yaml=./config/vector.yaml
generatorOptions:
  disableNameSuffixHash: true
