---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: e-books
  namespace: media
spec:
  storageClassName: e-books
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/mnt/user/E-Books"
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e-books
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: e-books
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kavita-claim
  namespace: media
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
