---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: networking
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflare-networks
    files:
      - ./cloudflare-networks.txt
generatorOptions:
  disableNameSuffixHash: true
