kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-server-claim
  namespace: security
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
