---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-blackbox-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/blackbox-exporter/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
