---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.11.230.254"
  METALLB_LB_RANGE: "10.11.230.50-10.11.230.60"
  METALLB_K8S_GATEWAY_ADDR: "10.11.230.50"
  METALLB_INGRESS_ADDR: "10.11.230.60"
