---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nfs-external-01
  namespace: storage
spec:
  releaseName: nfs-external
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-external-chart
        namespace: flux-system
  values:
    nfs:
      server: ${NAS_ADDR}
      path: /mnt/user/NFS_Mount

