---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nfs-external-01
  namespace: storage
spec:
  releaseName: nfs-external
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: configmap-nfs-external
    valuesKey: values.yaml
