---
apiVersion: v1
kind: Service
metadata:
  name: 3d-external
  namespace: external
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: 3d-external
  namespace: external
subsets:
    - addresses:
        - ip: ${3D_ADDR}
      ports:
        - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 3d-external
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 3d.techringer.net
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: 3d-external
            port:
              number: 80
