---
apiVersion: v1
kind: Service
metadata:
  name: unraid-external
  namespace: external
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: unraid-external
  namespace: external
subsets:
    - addresses:
        - ip: ${NAS_ADDR}
      ports:
        - port: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unraid-external
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: unraid.techringer.net
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana-external
            port:
              number: 8443
