---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcsv
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: configmap-minecraft
    valuesKey: values.yaml

