apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:ctU=,iv:x11Ch+vuVnE0oE99XlhVqKuwPAaYD9F/h5ieW/0LwkA=,tag:S1Dt4FHDyA70HknhNnxWzA==,type:str]
    token: ENC[AES256_GCM,data:yxY=,iv:U49IT1qo/cwt6UGFwq62v/DZK6Lk6usaJ11hktbkHdM=,tag:kQRjE1gwmYpBEPZ8r+YW5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5qwdkvzfz8aa6hhtrw25uu6wraay26xjxsth2thjcf2wp35lcysz8y3tr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ2ZxQm5ZTGdPRUh5Z2F2
            WENPdW1zYm4zK3NUeFl0Y1djTEpnQUd6QWtVCjViU0lmR3VndDMrTWZZa3kzUXUy
            RE44VVpxTjNvbVBMcFdpeGtlbUhyRlUKLS0tIGFVMjV4NVlmQzVpVzRKYTRzQzA2
            Q0JpSW4yc09VaEFWTnpOQnF6RVdMeWsKcTU1/xSEECMz2aQANXwxi4AhZGHSuQz1
            piwLku+29NJstzhuMAL7gldE5pw9p/eRjT5PlukjiZx98AKmaTuj8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-23T00:19:51Z"
    mac: ENC[AES256_GCM,data:vm7g33gzFKU0bCTX2R1q46iyRjqIsMwsMFyXxG/5DxZ87CkiIijlaDsptve262W3eVpvZ5TaD9waIH1IGBQYMqi1nAajTeuxgKGUNG/Xyoo5N4ihtthxaxF1sVcyk3inh7sBoluiqOCT8eJsmxsckhKfiOKLLDTBj5eQQqK8P88=,iv:GY0yht832cpKVnLF1WYO3B1p4UzGKlUPWfxWxfDwoBY=,tag:ORQYRJer1/zgkVFrbzGJJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
