---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-nfs-config
spec:
  storageClassName: node-red-nfs-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/usr/k8s/node-red
    server: ${SECRET_NAS1}
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: node-red-nfs-config
  resources:
    requests:
      storage: 1Mi
