---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botpress
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: botpress-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PG_PORT: "{{ .postgresql_postgresql_port }}"
        PG_HOST: "{{ .postgresql_host }}"
        PG_USER: "{{ .botpress_pg_user }}"
        PG_PASSWORD: "{{ .botpress_pg_password}}"
  dataFrom:
    - extract:
        key: database-main
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgresql_$1"
    - extract:
        key: botpress
      rewrite:
        - regexp:
            source: "(.*)"
            target: "botpress_$1"


