---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botpress
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: botpress/server
      pullPolicy: IfNotPresent
      tag: latest
    service:
      main:
        ports:
          http:
            port: &port 3000
    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: robot-angry-outline
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    env:
    - name: name
      value: "botpress"
    - name: PG_SSL
      value: "false"
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: botpress-secret
          key: PG_HOST
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: botpress-secret
          key: PG_PORT
    - name: PG_USER
      valueFrom:
        secretKeyRef:
          name: botpress-secret
          key: PG_USER
    - name: PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: botpress-secret
          key: PG_PASSWORD
    persistence:
      config:
        enabled: true
        mountPath: /botpress/data
        type: pvc
        existingClaim: botpress-claim
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 500Mi
