---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-xsoar
  namespace: bots
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-xsoar-secret
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: bots
        property: DISCORD_BOT_TOKEN
    - secretKey: DISCORD_GUILD
      remoteRef:
        key: bots
        property: DISCORD_GUILD
    - secretKey: XSOAR_API_KEY
      remoteRef:
        key: bots
        property: XSOAR_API_KEY
    - secretKey: XSOAR_URL
      remoteRef:
        key: bots
        property: XSOAR_URL
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: bots
        property: OPENAI_API_KEY
