---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: private-repo-techringer
  namespace: bots
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: private-repo-techringer
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .github }}` }}"
  data:
  - secretKey: github
    remoteRef:
        key: github
        property: techringer
