---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.20@sha256:86347342303d446e10915d1881b8f0a7fc4e2e6d33b68a5455a7a5880a1c47eb

    env:
      CACHE_DIR: /cache
      TZ: ${TIMEZONE}

    service:
      main:
        ports:
          http:
            port: &port 8083

    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/${THEME}.css"></head>';
            sub_filter_once on;
          hajimari.io/icon: book-open-page-variant
          hajimari.io/enable: "true"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      calibre:
        enabled: true
        existingClaim: nfs-calibre
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
      books:
        enabled: true
        existingClaim: e-books
        mountPath: /books

    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M
