## Job to build docker image
name: Push Notification

on:
  push:
    branches:
      - main

jobs:

  notify-complete:
    name: Flux Push
    runs-on: ubuntu-latest
    steps:

    # - name: Discord notification
    #   uses: Ilshidur/action-discord@master
    #   env:
    #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    #     uses: Ilshidur/action-discord@master
    #   with:
    #     args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} was updated.'
    - uses: sarisia/actions-status-discord@9904e3130b8905d5b973df25623f17672dcb3466 # v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Flux K8s update"
        description: "Flux was updated"
        #image: ${{ secrets.EMBED_IMAGE }}
        color: 0x0000ff
        url: "https://github.com/TechRinger/flux-cluster"
        #avatar_url: ${{ secrets.AVATAR_URL }}
